### ISSUE TITLE
Can't install Minetrack on Ubuntu 16.04

### ISSUE THREAD

**Issue by AppleMacOS** [Cryptkeeper/Minetrack#167]
I have installed the right version of node.js and npm and then I followed the steps in the README.md but when I do step 5 I get this error.

Node.js version: v14.2.0
npm version: 6.14.4
OS version: ubuntu-16.04-x86_64

```
> minetrack@5.4.1 build /root/minetrack5
> eslint assets/js/*.js && parcel build assets/html/index.html


Oops! Something went wrong! :(

ESLint: 6.8.0.

ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in /root/minetrack5/assets/js and its ancestors. If it found none, it then looked in your home directory.

If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! minetrack@5.4.1 build: `eslint assets/js/*.js && parcel build assets/html/index.html`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the minetrack@5.4.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-13T12_03_26_303Z-debug.log```

**Comment by hugmanrique** [comment]
This repo contains a `.eslintrc.json`file. Two things:

1. Do you have that file locally?
2. Are you running the build script from the repo dir (e.g. not inside assets/)?
3. Do you have eslint globally installed? This should be avoided. Check by running `eslint -v` in your home dir (~).

**Comment by AppleMacOS** [comment]
So I forgot to put the `.eslintrc.json` file and now it worked but when I go to the page it just says disconnected.

**Comment by hugmanrique** [comment]
Can you open your browser’s devtools and share the console logs? (redact anything sensitive)

**Comment by AppleMacOS** [comment]
Here is what I get in the console 
`[Error] Failed to load resource: the server responded with a status of 503 () (icomoon.32942e47.ttf, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (main.37a5e447.js.map, line 0)
[Error] WebSocket connection to 'wss://mydomain.com/' failed: Unexpected response code: 503 (x4)`

**Comment by hugmanrique** [comment]
Did you follow all installation steps? Mind also sharing the Node app logs?

**Comment by AppleMacOS** [comment]
I followed all the instructions, and here is the node app logs
``(node:12491) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
4:12:55 PM 13/5/20 - info: Started on 0.0.0.0:8080
4:12:55 PM 13/5/20 - error: Failed to ping play.skycade.net: getaddrinfo ENOTFOUND play.skycade.net
4:12:58 PM 13/5/20 - error: Failed to ping invadedlands.net: Socket timeout
4:12:58 PM 13/5/20 - error: Failed to ping mineman.club: Socket timeout
4:12:58 PM 13/5/20 - error: Failed to ping cubecraft.net: Socket timeout
4:12:58 PM 13/5/20 - error: Failed to ping mineplex.com: Socket timeout
4:12:58 PM 13/5/20 - error: Failed to ping play.skycade.net: getaddrinfo ENOTFOUND play.skycade.net
4:13:01 PM 13/5/20 - error: Failed to ping mineman.club: Socket timeout
4:13:01 PM 13/5/20 - error: Failed to ping cubecraft.net: Socket timeout
4:13:01 PM 13/5/20 - error: Failed to ping invadedlands.net: Socket timeout
4:13:01 PM 13/5/20 - error: Failed to ping mineplex.com: Socket timeout
4:13:01 PM 13/5/20 - error: Failed to ping play.skycade.net: getaddrinfo ENOTFOUND play.skycade.net`` I hope this is what you wanted.

**Comment by Cryptkeeper** [comment]
I have fixed some associated bugs in 5.4.2, I recommend updating: https://github.com/Cryptkeeper/Minetrack/releases/tag/v5.4.2

**Comment by AppleMacOS** [comment]
That fixed some errors but I'm still getting `Lost connection!` message when going to the web page.

**Comment by hugmanrique** [comment]
Your client logs suggest the server is rejecting WebSocket connections over `wss`. Do you have a valid TLS cert for that subdomain? What happens if you directly go to `https://sub.yourdomain.com`?

If you're proxying requests through Cloudflare, this may also indicate you have enabled the "I'm under attack" mode ([troubleshooting](https://community.cloudflare.com/t/community-tip-fixing-error-503-service-unavailable-service-temporarily-unavailable/44438)).

**Comment by AppleMacOS** [comment]
The SSL Certificate is from Cloudflare and is valid. This is what I see if I go to both https and http: [Screenshot](https://applescreenshots.net/i/Y25LaWb29kFnO.png) (It just keeps trying to reconnect)

I checked on Cloudflare and I do now have "I'm under attack" mode on.

**Comment by hugmanrique** [comment]
Last thing, can you open the devtools, go to the Network tab and share the full request (including headers, remove cookies and `User-Agent`) and response for `wss://sub.yourdomain.com`?

![Example](https://i.hugmanrique.me/v2/bHUlZ5eVab.png)

**Comment by AppleMacOS** [comment]
Here you go: https://applescreenshots.net/i/J9FHvmOLywZap.png

**Comment by hugmanrique** [comment]
Alright, that request looks correct, we now need the 503 response content and headers

**Comment by AppleMacOS** [comment]
The thing is it's giving me a 304, but I'll still send you a screenshot of it: https://applescreenshots.net/i/qSkyfi3eYydXb.png
https://applescreenshots.net/i/DEKMVh67OL8PC.png
https://applescreenshots.net/i/57lLA2ruTR0oM.png

**Comment by hugmanrique** [comment]
That's the wrong request, it should use the `wss` protocol instead of `https` (Chrome devtools displays the protocol upgrade).

**Comment by AppleMacOS** [comment]
This is all the requests that I get: https://applescreenshots.net/i/H9rl7LRa1mnFz.png

I'm using Chrome devtools and it doesn't display the protocol upgrade (Do I have to turn that on?)

**Comment by hugmanrique** [comment]
I cannot see the 503 error there, is it now connecting? We need the error when you tried to access it through the subdomain. The request is the first one (notice Schema is `wss`)

**Comment by AppleMacOS** [comment]
That is a screenshot of the network tab in the Devtools when trying to connect with the subdomain.

**Comment by hugmanrique** [comment]
Your Network tab and your console are saying different things: you get `[Error] WebSocket connection to 'wss://mydomain.com/' failed: Unexpected response code: 503 (x4)` but there's no failed request on the Network tab.

**Comment by AppleMacOS** [comment]
If I go into the requests Message in the network tab I get this `Error during WebSocket handshake: Unexpected response code: 200`

And when going to the console I still get those errors.

**Comment by isokissa3** [comment]
If you are using proxy pass for HTTP connections through Apache make sure you are also letting web socket connections to pass. I'm myself using Nginx and I had to add few new lines to my config to get it work

**Comment by AppleMacOS** [comment]
Okay so I am using proxy pass with Apache and I'm pretty new to it so what lines do I need to add?
This is what I have right now

```
<VirtualHost *:80>
    ServerName sub.domain.com

    <Location "/">
        ProxyPreserveHost On
        ProxyPass http://localhost:8080/
        ProxyPassReverse http://localhost:8080/
    </Location>
</VirtualHost>
```

**Comment by hugmanrique** [comment]
Ah, didn’t know you were proxying through Apache. Do the same as in this answer https://stackoverflow.com/a/27534443/4514467 but remove the first two RewriteCond (those are for Socket.io) and add a new one just like the last (and only one) with the wss:// protocol instead.

**Comment by AppleMacOS** [comment]
Okay so I followed that and added that line you told me to add and this is what I have now
```
<VirtualHost *:80>
    ServerName sub.domain.com

  <Location "/">
        RewriteEngine On
        RewriteRule /(.*)           wss://localhost:8080/$1 [P,L]

         ProxyPreserveHost On
         ProxyPass http://localhost:8080/
         ProxyPassReverse http://localhost:8080/
   </Location>
</VirtualHost>
```

But I get this error when visiting the web page now: https://applescreenshots.net/i/cSdeis12Rm54g.png

And this is the error in the error_log file 
`[Sat May 16 07:05:04.969350 2020] [proxy:error] [pid 27288] AH00961: WSS: failed to enable ssl support for 127.0.0.1:8080 (localhost)`

Like I said before I am new to this stuff and still learning so sorry if these are dumb questions.

**Comment by hugmanrique** [comment]
Sorry, my bad, maybe CF is terminating wss connections and making them use the insecure ws:// protocol. Tried proxying ws:// as the original SO answer?

**Comment by AppleMacOS** [comment]
I tried that and it just gives me a Bad request error. I don’t know what to do anymore.

**Comment by Cryptkeeper** [comment]
I don't have any experience with apache, but this is part of my nginx configuration:

```server {
	listen 80;
	server_name bedrock.minetrack.me;
	location / {
		proxy_pass http://localhost:8081;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
	}
}```

I added the Upgrade header after a StackOverflow answer I had seen. Perhaps you'll have some success with applying the apache equivalent.

**Comment by Cryptkeeper** [comment]
Yes, at least for nginx, you need to manually pass the Upgrade header etc when proxying WebSockets: https://nginx.org/en/docs/http/websocket.html

**Comment by hugmanrique** [comment]
In Apache that [should be handled](https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html) automatically by the wstunel module

**Comment by AppleMacOS** [comment]
I just moved to Nginx and used your configuration and changed the stuff I needed to change and it works! Thank you so much for the help.

**Comment by Cryptkeeper** [comment]
Glad to hear that worked out. Thanks for your help on the issue @hugmanrique @isokissa3
