### ISSUE TITLE
Chromium - Data display

### ISSUE THREAD

**Issue by Henriks9** [Cryptkeeper/Minetrack#253]
The data is not displayed when the database is large / displays many days in Firefox there are no problems.
![image](https://user-images.githubusercontent.com/30748992/119031101-fd4a0e80-b9aa-11eb-82fd-805e06744c0c.png)

**Comment by hugmanrique** [comment]
Could you open the site inspector (Ctrl+Shift+I) in Chrome and share any errors displayed on the terminal?

**Comment by Henriks9** [comment]
![image](https://user-images.githubusercontent.com/30748992/119180141-300a0a80-ba70-11eb-8a5b-5773b3d8bac0.png)

scale.js:35 Uncaught RangeError: Maximum call stack size exceeded
    at Function.value (scale.js:35)
    at Object.range (graph.js:292)
    at nt (uPlot.esm.js:1451)
    at Ot (uPlot.esm.js:2078)
    at Qt (uPlot.esm.js:2154)
    at $e (uPlot.esm.js:1218)
    at Wn (uPlot.esm.js:2804)
    at new zt (uPlot.esm.js:2816)
    at n.value (graph.js:218)
    at WebSocket._webSocket.onmessage (socket.js:110)

> Could you open the site inspector (Ctrl+Shift+I) in Chrome and share any errors displayed in the terminal?

**Comment by hugmanrique** [comment]
I'm pretty busy atm, but this is a good first-time issue for anyone interested 😀 The cause of the error is https://github.com/Cryptkeeper/Minetrack/blob/86477821751951c86256fe6731befb320e5a18ad/assets/js/scale.js#L35 and is due to using the ES6 spread operator on a large array (see https://stackoverflow.com/a/63706516 for details). The fix is to use `Math.Max.apply`.

**Comment by Cryptkeeper** [comment]
The version 5.5.9 release preview should fix this issue for you. It will be merged into master in a few days. Thanks for the diagnostics @hugmanrique.

**Comment by Cryptkeeper** [comment]
Fixed in version 5.5.9

**Comment by Henriks9** [comment]
Hey,
in Edge the error still occur 


![](https://cdn.henriks9.ovh/3ec8aq0.png)

**Comment by hugmanrique** [comment]
Make sure you've purged your browser cache. See https://support.google.com/accounts/answer/32050 for how to do this on Chrome and Edge. Also, make sure your site isn't caching the JS assets for a long time; I've lost countless hours debugging code only for CloudFlare to be caching an old version.
