### ISSUE TITLE
minetrack.me keeps socket timeouting on every server

### ISSUE THREAD

**Issue by gameshowrecaps** [Cryptkeeper/Minetrack#314]
Every server keeps socket timeouting on the main minetrack.me site.

**Comment by hugmanrique** [comment]
You can try increasing the ping rate and the connection timeout in the `config.json` file and see if that fixes it. You might be getting rate-limited by the servers.

**Comment by TehNeon** [comment]
> You can try increasing the ping rate and the connection timeout in the `config.json` file and see if that fixes it. You might be getting rate-limited by the servers.

They're referring to the live instance that Cryptkeeper maintains. If you go to https://minetrack.me/ currently you'll see it, or view the screenshot I've attached to this.

![image](https://user-images.githubusercontent.com/3179302/185803640-dc61f47b-c47a-451a-a1f5-d2564bb11567.png)

**Comment by hugmanrique** [comment]
Ah, perhaps the server host is rate-limiting us. Crypt, mind taking a look?

**Comment by gameshowrecaps** [comment]
Looks like the issue is fixed.

**Comment by hugmanrique** [comment]
Not really, I'm still seeing socket timeouts. Mind reopening the issue?

**Comment by ClydeplayzYT590** [comment]
> Looks like the issue is fixed.

It keeps fixing itself and after 2 hours the issue appears again

**Comment by Cryptkeeper** [comment]
Best I can tell, the DNS servers the DigitalOcean droplet used are not responding. I deployed a new droplet when the issue first showed up, but it started again. I swapped the nameservers to 1.1.1.1 and everything looks fine, but I'll keep an eye on it for any regressions.
